intelligent-agent/redeem

tests/gcode/MockPrinter.py
incorrect indentation for test config file
=> incorrect indentation for test config file

.circleci/config.yml
For public projects, circleci is free continuous integration. Simple config to run the test suite on pull requests and commits.
=> Continuous integration with CircleCI

.gitignore, redeem/TextWriter.py, redeem/gcodes/G2_G3.py, redeem/gcodes/GCodeCommand.py, setup.py
adding description for G2/G3 arc commands
also enabling formatted descriptions using python's docutils
=> arc command descriptions

redeem/gcodes/GCodeCommand.py, redeem/gcodes/M116.py, redeem/gcodes/M23.py
excess import statements refer to packages that are not needed
=> M23 fix for incorrect imports

configs/default.cfg, redeem/Printer.py, redeem/Stepper.py
These changes address compatibility issues with the older A4A board raised in #21
=> modifications for compatibility with Replicape Rev A4A

requirements.txt, setup.py
`setup.py` uses `requirements.txt` as its source for requirements and dependency.
=> consolidate and unify reqiurements

configs/default.cfg, redeem/Redeem.py, redeem/gcodes/M106_M107.py
Small addition for M106 g-code to change PWM frequency.  
should be compliant with reprap g-code style
http://reprap.org/wiki/G-code#M106:_Fan_On
this should be further developed to make it persistent, but that need more changes on code..
=> Add F option for controlling PWM freq to M106

redeem/PathPlanner.py, redeem/SDCardManager.py, redeem/gcodes/G28.py, redeem/gcodes/M2x.py
While SD printing was working quite well the integration with OctoPrint was not so good. This mostly consisted of timeouts and not updating the print status while running. I've added a few small changes that allow for more expected behaviour from OP, at least in my use.
=> modifications to get SD printing to work as expected with OctoPrint

redeem/PruFirmware.py
Added import of Printer as it was previously undefined when used for indexing axes
=> Add import of Printer to PruFirmware.py

redeem/GCodeProcessor.py
This is really just a hack. The parsing code should
Be rewritten to filter out those “?” Lines in a
Better manner.
=> Information requests are not handled properly

requirements.txt, setup.py
=> Create Compatibility with PIP 10

redeem/gcodes/M280.py, redeem/gcodes/M574.py
Resubmitting after fixing some tangled branches in my repo.
=> Make M280 and M574 buffered commands

docs/gulpfile.js
Slowly, but surely removing styling mis-matches
=> Style Corrections

redeem/gcodes/M2x.py
=> Make M23 output conform to Octoprint expectations

redeem/Pipe.py, redeem/Redeem.py
Currently validating this on my printer. Will check back in after a few prints.
=> Remove dependency on socat/tty0tty by durectly creating and using PTYs

redeem/Pipe.py
Python seems to get upset and throw an invalid seek IOError if we
read and write to the same pipe through the same file object on
two threads. Go back to opening two objects - one for reading and
one for writing.
=> open separate files to read and write to a pipe

redeem/EndStop.py
Another case where an import got lost in a merge
=> Import logging to Endstop.py

redeem/gcodes/M2x.py
These commits improve the way that gcode files are managed and reported.
It suppresses the listing of hidden artifact files in the SD directory
It rebases and corrects the changes from PR #145
=> Improvements to the handling of Gcode files

redeem/path_planner/PruTimer.cpp, redeem/path_planner/PruTimer.h
=> preserve uint64_t times in the PRU's block accounting

redeem/path_planner/PruTimer.cpp, redeem/path_planner/PruTimer.h
=> PRU queue isn't full by time if it's shutting down

redeem/_version.py, setup.cfg, versioneer.py
Succeeds locally. It may need a tag in the master repo to pass the Travis tests there
=> Versioning

redeem/Cooler.py
Speed up shutdowns by making the cooler threads stop on an Event.
Courtesy of @Wackerbarth
=> Add Event thread to stop fans rapidly

redeem/Alarm.py, redeem/CascadingConfigParser.py, redeem/EndStop.py, redeem/IOManager.py, redeem/Key_pin.py, redeem/Pipe.py, redeem/Redeem.py, redeem/Servo.py, redeem/gcodes/M2x.py
Also includes some additional PY2/PY3 compatibility
=> Some cleanup for IOManager

configs/series1.cfg
=> Typo in series1.cfg

redeem/gcodes/M2x.py
This is a rebase of the part of PR #65 which applies to this topic.
=> Add case insensitivity to M23
